server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/identity_service?createDatabaseIfNotExist=true"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
jwt:
  signer-key: "8e/o3toCJW4Kngf7RVbMKZo8Okhx+TH1V1vI3cYwW2qlLvynC2DME40oIqqUxRzs"
  valid-duration: 15 #second
  refreshable-duration: 120 #second (usually days or weeks)