server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/identity_service?createDatabaseIfNotExist=true"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  signerKey: "8e/o3toCJW4Kngf7RVbMKZo8Okhx+TH1V1vI3cYwW2qlLvynC2DME40oIqqUxRzs"